### ISSUE TITLE
Release v6.0.1

### ISSUE THREAD

**Issue by SavenkovIgor** [SavenkovIgor/QmlSandboxExtension#96]
### Tasks

- [x] Add changes to Changelog
- [x] Check that all examples at `examples` folder are working
- [x] Up version in `package.json`
- [x] Make release tag with changes from Changelog
